stages:
  prepare_data:
    cmd: python src/data/prepare_data.py
    deps:
      - src/data/prepare_data.py
      - data/raw/MachineLearningRating_v3.txt
    outs:
      - data/processed/insurance_clean.csv
