stages:
  prepare_data:
    cmd: python -m src.data.prepare_data
    deps:
      - src/data/prepare_data.py
      - data/raw/MachineLearningRating_v3.txt
    outs:
      - data/processed/insurance_clean.csv
